### ISSUE TITLE
Error exporting hail table to elastic search

### ISSUE THREAD

**Issue by Jack-Ow** [broadinstitute/hail-elasticsearch-pipelines#118]
I've tried to export the hail table to elastic search with the following parameters and encountered error. If I removed the "raised NotImplementedError" in the code, I get a different set of errors ([run.log](https://github.com/macarthur-lab/hail-elasticsearch-pipelines/files/2939300/run.log)).

 /root/export_ht_to_es.py --ht-url 's3://mybucket/gnomad.exomes.r2.1.sites.ht' --host 'XX.XX.XX.XX' --port XXXX --index-name 'data' --index-type 'variant' --num-shards 10 --es-block-size 5000

Traceback (most recent call last):
  File "/root/export_ht_to_es.py", line 55, in <module>
    main(args)
  File "/root/export_ht_to_es.py", line 41, in main
    verbose=True
  File "/root/hail_scripts/v02/utils/elasticsearch_client.py", line 143, in export_table_to_elasticsearch
    disable_index_for_fields=disable_index_for_fields,
  File "/root/hail_scripts/v02/utils/elasticsearch_utils.py", line 51, in elasticsearch_schema_for_table
    properties = _elasticsearch_mapping_for_type(table.row_value.dtype)["properties"]
  File "/root/hail_scripts/v02/utils/elasticsearch_utils.py", line 23, in _elasticsearch_mapping_for_type
    return {"properties": {field: _elasticsearch_mapping_for_type(dtype[field]) for field in dtype.fields}}
  File "/root/hail_scripts/v02/utils/elasticsearch_utils.py", line 23, in <dictcomp>
    return {"properties": {field: _elasticsearch_mapping_for_type(dtype[field]) for field in dtype.fields}}
  File "/root/hail_scripts/v02/utils/elasticsearch_utils.py", line 25, in _elasticsearch_mapping_for_type
    element_mapping = _elasticsearch_mapping_for_type(dtype.element_type)
  File "/root/hail_scripts/v02/utils/elasticsearch_utils.py", line 23, in _elasticsearch_mapping_for_type
    return {"properties": {field: _elasticsearch_mapping_for_type(dtype[field]) for field in dtype.fields}}
  File "/root/hail_scripts/v02/utils/elasticsearch_utils.py", line 23, in <dictcomp>
    return {"properties": {field: _elasticsearch_mapping_for_type(dtype[field]) for field in dtype.fields}}
  File "/root/hail_scripts/v02/utils/elasticsearch_utils.py", line 31, in _elasticsearch_mapping_for_type
    raise NotImplementedError
NotImplementedError

Thanks and Best,
Jack

**Comment by Jack-Ow** [comment]
I think I've zoomed down to this section of the code in elasticsearch_utils.py.
`def _elasticsearch_mapping_for_type(dtype):`
`    if isinstance(dtype, hl.tstruct):`
`        return {"properties": {field: _elasticsearch_mapping_for_type(dtype[field]) for field in dtype.fields}}`
`    if isinstance(dtype, (hl.tarray, hl.tset)):	`
`        print(dtype.element_type)`
`        element_mapping = _elasticsearch_mapping_for_type(dtype.element_type)        `
`        if isinstance(dtype.element_type, hl.tstruct):`
`            element_mapping["type"] = "nested"`
`        return element_mapping`
`    if dtype in HAIL_TYPE_TO_ES_TYPE_MAPPING:`
`        print("HAIL_TYPE_TO_ES_TYPE_MAPPING:" + dtype)`
`        return {"type": HAIL_TYPE_TO_ES_TYPE_MAPPING[dtype]}`
`    raise NotImplementedError`

Below is a type in the data that could not be handled by the code giving that error. 

faf: array<struct{meta: dict<str, str>, faf95: float64, faf99: float64}>

**Comment by nawatts** [comment]
Hi @Jack-Ow,

Exporting dicts to Elasticsearch is not supported. Since each row of a Hail table could have different keys in the dict field, defining an Elasticsearch field for each key could lead to a "[mapping explosion](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#mapping-limit-settings)". It would also require aggregating the table to build the ES mapping instead of inspecting the row data type.

To work around this, you could convert the dict either to a struct with a field per key(if there are a reasonable number of possible keys) or to a list of structs with `key` and `value` fields.
