### ISSUE TITLE
Error in load_clinvar_to_es in v0.1

### ISSUE THREAD

**Issue by SimonLi5601** [broadinstitute/hail-elasticsearch-pipelines#123]
File "/opt/seqr/hail-elasticsearch-pipelines/hail_scripts/v01/load_clinvar_to_es.py", line 100, in <module>
    summary = vds.summarize()
  File "<decorator-gen-442>", line 2, in summarize
  File "/opt/seqr/hail-elasticsearch-pipelines/hail_builds/v01/hail-v01-10-8-2018-90c855449.zip/hail/java.py", line 121, in handle_py4j
hail.java.FatalError: NumberFormatException: For input string: "NW_003315947.1"

I did some search and is this related to VCF header?
Thanks

**Comment by SimonLi5601** [comment]
I looked at the ClinVar file and found "NW_003315947.1" is in the #CHROM column. I guess that's a problem? Where the data structure was defined for this column?

**Comment by SimonLi5601** [comment]
I think I located the cause of the [problem](https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/29051791d36b4cb7c54f066f6923959813f7f773/hail_scripts/v01/utils/computed_fields.py#L396). It doesn't handle the case I mentioned above. I am wondering did you encounter the same problem?

**Comment by bw2** [comment]
@SimonLi5601 I do see this issue in the GRCh37 version of clinvar.  
As a workaround, you can add `--subset 1-22XY` to discard records with unusual chromosome names. Let me know if this doesn't work for you.

**Comment by SimonLi5601** [comment]
@bw2 Oh, I see, that should work. I will get it a try to see if any other problem.Thanks!

**Comment by SimonLi5601** [comment]
@bw2 Hi Ben. I kind of addressed the issue mentioned above. But I have another issue for mapping a VDS field to a ElasticSearch filed.
  File "/opt/seqr/hail-elasticsearch-pipelines/hail_scripts/v01/utils/elasticsearch_utils.py", line 87, in _map_vds_type_to_es_type
    raise ValueError("Unexpected VDS type: %s" % str(type_name))
ValueError: Unexpected VDS type: Set[Struct{db:String,name:String}]

Please see the partial schema for the KeyTable below and the domains are a Set of Struct.
export_kt_to_elasticsearch - KeyTable schema: Struct{
     allele_id: Int,
     chrom: String,
     clinical_significance: String,
     domains: Set[Struct{
         db: String,
         name: String
     }],
     gene_ids: Set[String],
     gold_stars: Int,

I added a trick without looking into deeply, but it seems not working, do you have any suggestions? Thanks!

VDS_TO_ES_TYPE_MAPPING.update({
   'Array[Struct]': 'nested',
+  'Set[Struct]': 'nested',
 })

**Comment by SimonLi5601** [comment]
It seems that data structure has been changed during annotate_variants_expr call. 
I made a ad-hoc modification on my local in this [toSet](https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/4322dc60a22eb42d1ac35a90ad4df158c0421c61/hail_scripts/v01/utils/computed_fields.py#L331)  -> toArray and it works. I am not sure if I have different VDS schema from the upstream pipeline from you.

**Comment by bw2** [comment]
Hi Simon, glad you found a work-around. 
I'm not sure what the issue is, and would need to do more troubleshooting to reproduce this. 
@knguyen142 is making good progress with converting all pipelines to hail 0.2, so if your patch is working fine, perhaps it's best to stay with that until the 0.2 pipelines are ready.

**Comment by SimonLi5601** [comment]
Hi Ben, thanks for the update. Glad to hear that. Yes, currently I am working on this (more on load_dataset_to_es)  just to have a demo dataset to be used in seqr application. We will stay tuned for the progress of v 0.2.
