### ISSUE TITLE
Error when trying to load VCF in ES

### ISSUE THREAD

**Issue by mark-sp** [broadinstitute/hail-elasticsearch-pipelines#126]
I came across your scripts when trying to import my VCFs file into a local ES. I am trying to use "hail_scripts/v01/load_dataset_to_es.py" but it crashes regardless the parameters I use.

The error seems to be related with the use of a ES mapping function. I have tried both python3 and 2.7 with identic reults. Have you seen this bug before? Am I doing something wrong?
     
`28 # elasticsearch field types for arrays are the same as for simple types:`
`29 for vds_type, es_type in VDS_TO_ES_TYPE_MAPPING.items():`
`30     VDS_TO_ES_TYPE_MAPPING.update({"Array[%s]" % vds_type: es_type})`
`31     VDS_TO_ES_TYPE_MAPPING.update({"Set[%s]" % vds_type: es_type})`
`RuntimeError: dictionary changed size during iteration`

**Comment by nawatts** [comment]
Hi @mark-sp,

I only see this error when using Python 3.
```
~/hail-elasticsearch-pipelines $ python2 hail_scripts/v01/utils/elasticsearch_utils.py
~/hail-elasticsearch-pipelines $ python3 hail_scripts/v01/utils/elasticsearch_utils.py
Traceback (most recent call last):
  File "hail_scripts/v01/utils/elasticsearch_utils.py", line 29, in <module>
    for vds_type, es_type in VDS_TO_ES_TYPE_MAPPING.items():
RuntimeError: dictionary changed size during iteration
```

In Python 2, `VDS_TO_ES_TYPE_MAPPING.items()` returns a list so this is not iterating over the `VDS_TO_ES_TYPE_MAPPING` dict itself.

In Python 3 however, `items` returns an iterator and thus updating `VDS_TO_ES_TYPE_MAPPING` inside the for loop causes the RuntimeError you're seeing. To make this work in Python 3, you could create a list with the `items` iterator. However, the Hail 0.1 scripts in this repository are not written to support Python 3 so you're likely to run into other compatibility issues.
```python
for vds_type, es_type in list(VDS_TO_ES_TYPE_MAPPING.items()):
    VDS_TO_ES_TYPE_MAPPING.update({"Array[%s]" % vds_type: es_type})
    VDS_TO_ES_TYPE_MAPPING.update({"Set[%s]" % vds_type: es_type})
```
