### ISSUE TITLE
Error when uploading multiple vcf files together for family set | HailException: arguments refer to no file

### ISSUE THREAD

**Issue by Toseph** [broadinstitute/hail-elasticsearch-pipelines#173]
Hi all, 

I have been successful in uploading individual vcf samples to our seqr local installation, but hail fails when I try and upload multiple vcf files together (still in the same directory). If I upload them individually only the child sample takes, but seqr won't accept index of the parent vcf files saying it expects to see the other already there. 

When I attempt to upload multiple vcf's for the family set together I get this error instead. 

Here is my bash script (this has worked for single samples)
`#!/bin/bash`

`GENOME_VERSION="37"        # should be "37" or "38"
SAMPLE_TYPE="WES"          # can be "WES" or "WGS"
DATASET_TYPE="VARIANTS"    # can be "VARIANTS" (for GATK VCFs) or "SV" (for Manta VCFs)
PROJECT_GUID="R0001_project1"   # should match the ID in the url of the project page
INPUT_VCF="file1.vcf.gz,file2.vcf.gz,file3.vcf.gz"`

`python2.7 gcloud_dataproc/submit.py --run-locally --driver-memory 40G --executor-memory 40G hail_scripts/v01/load_dataset_to_es.py --spark-home $SPARK_HOME --genome-version $GENOME_VERSION --project-guid $PROJECT_GUID --sample-type $SAMPLE_TYPE --dataset-type $DATASET_TYPE --skip-validation  --exclude-hgmd --vep-block-size 100 --es-block-size 10 --num-shards 1 --hail-version 0.1  --output-vds GEN14 --use-nested-objects-for-vep --use-nested-objects-for-genotypes --cpu-limit 8 $INPUT_VCF`

It won't let me run it without supplying --output-vds to name the whole set with a prefix. 
I was also told to try using wildcard * so file*.vcf.gz but it seems like it only uses the first matching file. 

Without wildcard I get this error, 

`[thasan@seqr03 hail_elasticsearch_pipelines]$ ./multi-upload.sh /usr/local/seqr/seqr/../bin/spark-2.0.2-bin-hadoop2.7/bin/spark-submit --master local[8] --driver-memory 40G --executor-memory 40G --num-executors 10 --conf spark.driver.extraJavaOptions=-Xss4M --conf spark.executor.extraJavaOptions=-Xss4M --conf spark.executor.memoryOverhead=5g --conf spark.driver.maxResultSize=30g --conf spark.kryoserializer.buffer.max=1g --conf spark.memory.fraction=0.1 --conf spark.default.parallelism=1 --jars hail_builds/v01/hail-v01-10-8-2018-90c855449.jar --conf spark.driver.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar --conf spark.executor.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar --py-files hail_builds/v01/hail-v01-10-8-2018-90c855449.zip "hail_scripts/v01/load_dataset_to_es.py" "--genome-version" "37" "--project-guid" "R0001_project1" "--sample-type" "WES" "--dataset-type" "VARIANTS" "--skip-validation" "--exclude-hgmd" "--vep-block-size" "100" "--es-block-size" "10" "--num-shards" "1" "--output-vds" "GEN14" "--use-nested-objects-for-vep" "--use-nested-objects-for-genotypes" "file1.vcf.gz,file2.vcf.gz,file3.vcf.gz" --username 'thasan' --directory 'seqr03.nygenome.org:/usr/local/seqr/seqr/hail_elasticsearch_pipelines'`

`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support Requirement already satisfied: elasticsearch in /usr/lib/python2.7/site-packages (7.0.4) Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python2.7/site-packages (from elasticsearch) (1.25.3) WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.` 
`You should consider upgrading via the 'pip install --upgrade pip' command. 2019-10-24 13:25:44,312 INFO Index name: r0001_project1__wes__grch37__variants__20191024 2019-10-24 13:25:44,312 INFO Command args: /usr/local/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py --index r0001_project1__wes__grch37__variants__20191024 2019-10-24 13:25:44,315 INFO Parsed args:
{'cpu_limit': None, 'create_snapshot': False, 'dataset_type': 'VARIANTS', 'directory': 'seqr03.nygenome.org:/usr/local/seqr/seqr/hail_elasticsearch_pipelines', 'discard_missing_genotypes': False, 'dont_delete_intermediate_vds_files': False, 'dont_update_operations_log': False, 'es_block_size': 10, 'exclude_1kg': False, 'exclude_cadd': False, 'exclude_clinvar': False, 'exclude_dbnsfp': False, 'exclude_eigen': False, 'exclude_exac': False, 'exclude_gene_constraint': False, 'exclude_gnomad': False, 'exclude_gnomad_coverage': False, 'exclude_hgmd': True, 'exclude_mpc': False, 'exclude_omim': False, 'exclude_primate_ai': False, 'exclude_splice_ai': False, 'exclude_topmed': False, 'exclude_vcf_info_field': False, 'export_vcf': False, 'fam_file': None, 'family_id': None, 'filter_interval': '1-MT', 'genome_version': '37', 'host': 'localhost', 'ignore_extra_sample_ids_in_tables': False, 'ignore_extra_sample_ids_in_vds': False, 'index': 'r0001_project1__wes__grch37__variants__20191024', 'individual_id': None, 'input_dataset': 'file1.vcf.gz,file2.vcf.gz,file3.vcf.gz', 'max_samples_per_index': 250, 'not_gatk_genotypes': False, 'num_shards': 1, 'only_export_to_elasticsearch_at_the_end': False, 'output_vds': 'GEN14', 'port': '9200', 'project_guid': 'R0001_project1', 'remap_sample_ids': None, 'sample_type': 'WES', 'skip_annotations': False, 'skip_validation': True, 'skip_vep': False, 'skip_writing_intermediate_vds': False, 'start_with_sample_group': 0, 'start_with_step': 0, 'stop_after_step': 1000, 'subset_samples': None, 'use_child_docs_for_genotypes': False, 'use_nested_objects_for_genotypes': True, 'use_nested_objects_for_vep': True, 'use_temp_loading_nodes': False, 'username': 'thasan', 'vep_block_size': 100}` 
`2019-10-24 13:25:44,315 INFO ==> create HailContext Running on Apache Spark version 2.0.2 SparkUI available at http://10.1.27.167:4040 Welcome to __ __ <>__ / /_/ /__ __/ / / __ / _ / / /
// //_,//_/ version 0.1-105a497
2019-10-24 13:25:46,449 INFO is_running_locally = True
2019-10-24 13:25:46,449 INFO`

`=============================== pipeline - step 0 - run vep =============================== 2019-10-24 13:25:46,449` 
`INFO ==> import: file1.vcf.gz,file2.vcf.gz,file3.vcf.gz 2019-10-24 13:25:46 Hail: WARN: file1.vcf.gz,file2.vcf.gz,file3.vcf.gz' refers to no files
Traceback (most recent call last):
File "/usr/local/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 900, in
run_pipeline()
File "/usr/local/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 867, in run_pipeline
hc, vds = step0_init_and_run_vep(hc, vds, args)
File "/usr/local/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 162, in wrapper
result = f(*args, **kwargs)
File "/usr/local/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 419, in step0_init_and_run_vep
not_gatk_genotypes=args.not_gatk_genotypes,
File "/usr/local/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/utils/vds_utils.py", line 67, in read_in_dataset
vds = hc.import_vcf(input_path, force_bgz=True, min_partitions=10000, generic=not_gatk_genotypes)
File "", line 2, in import_vcf
File "/usr/local/seqr/seqr/hail_elasticsearch_pipelines/hail_builds/v01/hail-v01-10-8-2018-90c855449.zip/hail/java.py", line 121, in handle_py4j
hail.java.FatalError: HailException: arguments refer to no files`

`Java stack trace:
is.hail.utils.HailException: arguments refer to no files
at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:6)
at is.hail.utils.package$.fatal(package.scala:27)
at is.hail.io.vcf.LoadVCF$.globAllVCFs(LoadVCF.scala:105)
at is.hail.HailContext.importVCFs(HailContext.scala:544)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:280)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:214)
at java.lang.Thread.run(Thread.java:748)`

`Hail version: 0.1-105a497
Error summary: HailException: arguments refer to no files
Traceback (most recent call last):
File "gcloud_dataproc/submit.py", line 99, in
subprocess.check_call(command, shell=True)
File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/seqr/seqr/../bin/spark-2.0.2-bin-hadoop2.7/bin/spark-submit --master local[8] --driver-memory 40G --executor-memory 40G --num-executors 10 --conf spark.driver.extraJavaOptions=-Xss4M --conf spark.executor.extraJavaOptions=-Xss4M --conf spark.executor.memoryOverhead=5g --conf spark.driver.maxResultSize=30g --conf spark.kryoserializer.buffer.max=1g --conf spark.memory.fraction=0.1 --conf spark.default.parallelism=1 --jars hail_builds/v01/hail-v01-10-8-2018-90c855449.jar --conf spark.driver.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar --conf spark.executor.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar --py-files hail_builds/v01/hail-v01-10-8-2018-90c855449.zip "hail_scripts/v01/load_dataset_to_es.py" "--genome-version" "37" "--project-guid" "R0001_project1" "--sample-type" "WES" "--dataset-type" "VARIANTS" "--skip-validation" "--exclude-hgmd" "--vep-block-size" "100" "--es-block-size" "10" "--num-shards" "1" "--output-vds" "GEN14" "--use-nested-objects-for-vep" "--use-nested-objects-for-genotypes" "file1.vcf.gz,file2.vcf.gz,file3.vcf.gz" --username 'thasan' --directory 'seqr03.nygenome.org:/usr/local/seqr/seqr/hail_elasticsearch_pipelines'
' returned non-zero exit status 1`

**Comment by nawatts** [comment]
Though using a comma separated list of VCFs is documented, I don't see anything that would split it into the list expected by [import_vcf](https://hail.is/docs/0.1/hail.HailContext.html?highlight=import_vcf#hail.HailContext.import_vcf). @bw2 do you know if this option is supposed to work? It was documented in 0c83ec642059f941ec78da64583d9f8cf98704d4.

The output "INFO ==> import: file1.vcf.gz,file2.vcf.gz,file3.vcf.gz" (from [read_in_dataset](https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/70de273b3cddce626e560b508be151f3d8ffa6b4/hail_scripts/v01/utils/vds_utils.py#L48)) and "Hail: WARN: file1.vcf.gz,file2.vcf.gz,file3.vcf.gz' refers to no files" definitely looks like the comma separate list is _not_ being split and Hail is trying to import one file named "file1.vcf.gz,file2.vcf.gz,file3.vcf.gz".

I believe the wildcard is the way to go. [import_vcf](https://hail.is/docs/0.1/hail.HailContext.html?highlight=import_vcf#hail.HailContext.import_vcf) accepts [Hadoop glob patterns](https://hail.is/docs/0.1/hadoop_glob_patterns.html#sec-hadoop-glob) as input. It looks like the reason that your script is loading only one file when using the wildcard may be because the glob is being expanded by the shell and the result passed to `load_dataset_to_es.py` instead of the glob itself. Try quoting `$INPUT_VCF` in your bash script.

For example, compare the results of these two scripts:
```
touch file1.vcf file2.vcf file3.vcf
FILES="file*.vcf"
echo $FILES
```

```
touch file1.vcf file2.vcf file3.vcf
FILES="file*.vcf"
echo "$FILES"
```

**Comment by Toseph** [comment]
Sorry to trouble you again before the weekend, going to make two comments to show my input and output with and without quotes around $INPUT_VCF 

In this example it does not recognize file2 or file3
`load_dataset_to_es.py: error: unrecognized arguments: file2.vcf.gz file3.vcf.gz`


Input w/o quotes: 
`#!/bin/bash`

`GENOME_VERSION="37"        # should be "37" or "38"
SAMPLE_TYPE="WES"          # can be "WES" or "WGS"
DATASET_TYPE="VARIANTS"    # can be "VARIANTS" (for GATK VCFs) or "SV" (for Manta VCFs)
PROJECT_GUID="R0001_project1"   # should match the ID in the url of the project page
INPUT_VCF="file*gz"`

`python2.7 gcloud_dataproc/submit.py --run-locally --driver-memory 40G --executor-memory 40G hail_scripts/v01/load_dataset_to_es.py --spark-home $SPARK_HOME --genome-version $GENOME_VERSION --project-guid $PROJECT_GUID --sample-type $SAMPLE_TYPE --dataset-type $DATASET_TYPE --skip-validation  --exclude-hgmd --vep-block-size 100 --es-block-size 10 --num-shards 1 --hail-version 0.1 --use-nested-objects-for-vep --use-nested-objects-for-genotypes --cpu-limit 8 --output-vds GEN14 $INPUT_VCF`

Output:
`./manual-upload.sh`
`/usr/local/seqr/seqr/../bin/spark-2.0.2-bin-hadoop2.7/bin/spark-submit         --master local[8]         --driver-memory 40G         --executor-memory 40G         --num-executors 10         --conf spark.driver.extraJavaOptions=-Xss4M         --conf spark.executor.extraJavaOptions=-Xss4M         --conf spark.executor.memoryOverhead=5g         --conf spark.driver.maxResultSize=30g         --conf spark.kryoserializer.buffer.max=1g         --conf spark.memory.fraction=0.1         --conf spark.default.parallelism=1         --jars hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.driver.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.executor.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --py-files hail_builds/v01/hail-v01-10-8-2018-90c855449.zip         "hail_scripts/v01/load_dataset_to_es.py" "--genome-version" "37" "--project-guid" "R0001_project1" "--sample-type" "WES" "--dataset-type" "VARIANTS" "--skip-validation" "--exclude-hgmd" "--vep-block-size" "100" "--es-block-size" "10" "--num-shards" "1" "--use-nested-objects-for-vep" "--use-nested-objects-for-genotypes" "--output-vds" "GEN14" "file1.vcf.gz" "file2.vcf.gz" "file3.vcf.gz" --username 'thasan' --directory 'seqr03.nygenome.org:/usr/local/seqr/seqr/hail_elasticsearch_pipelines'`

`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: elasticsearch in /usr/lib/python2.7/site-packages (7.0.4)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python2.7/site-packages (from elasticsearch) (1.25.3)
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
usage: load_dataset_to_es.py [-h] --genome-version {37,38} [--skip-vep]
                             [--skip-annotations] [--skip-validation]
                             [--skip-writing-intermediate-vds]
                             [--filter-interval FILTER_INTERVAL]
                             [--remap-sample-ids REMAP_SAMPLE_IDS]
                             [--subset-samples SUBSET_SAMPLES]
                             [--ignore-extra-sample-ids-in-tables]
                             [--ignore-extra-sample-ids-in-vds]
                             [--fam-file FAM_FILE]
                             [--max-samples-per-index MAX_SAMPLES_PER_INDEX]
                             [--export-vcf] --project-guid PROJECT_GUID
                             [--family-id FAMILY_ID]
                             [--individual-id INDIVIDUAL_ID] --sample-type
                             {WES,WGS,RNA} --dataset-type {VARIANTS,SV}
                             [--not-gatk-genotypes] [--index INDEX]
                             [--host HOST] [--port PORT]
                             [--num-shards NUM_SHARDS]
                             [--use-temp-loading-nodes]
                             [--vep-block-size VEP_BLOCK_SIZE]
                             [--es-block-size ES_BLOCK_SIZE]
                             [--cpu-limit CPU_LIMIT]
                             [--use-nested-objects-for-vep]
                             [--use-nested-objects-for-genotypes]
                             [--use-child-docs-for-genotypes]
                             [--discard-missing-genotypes] [--exclude-dbnsfp]
                             [--exclude-1kg] [--exclude-omim]
                             [--exclude-gene-constraint] [--exclude-eigen]
                             [--exclude-cadd] [--exclude-gnomad]
                             [--exclude-exac] [--exclude-topmed]
                             [--exclude-clinvar] [--exclude-hgmd]
                             [--exclude-mpc] [--exclude-primate-ai]
                             [--exclude-splice-ai] [--exclude-gnomad-coverage]
                             [--exclude-vcf-info-field]
                             [--dont-update-operations-log]
                             [--dont-delete-intermediate-vds-files]
                             [--only-export-to-elasticsearch-at-the-end]
                             [--create-snapshot]
                             [--start-with-step {0,1,2,3,4}]
                             [--stop-after-step {0,1,2,3,4}]
                             [--start-with-sample-group START_WITH_SAMPLE_GROUP]
                             [--username USERNAME] [--directory DIRECTORY]
                             [--output-vds OUTPUT_VDS]
                             input_dataset`
`load_dataset_to_es.py: error: unrecognized arguments: file2.vcf.gz file3.vcf.gz
Traceback (most recent call last):
  File "gcloud_dataproc/submit.py", line 99, in <module>
    subprocess.check_call(command, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/seqr/seqr/../bin/spark-2.0.2-bin-hadoop2.7/bin/spark-submit         --master local[8]         --driver-memory 40G         --executor-memory 40G         --num-executors 10         --conf spark.driver.extraJavaOptions=-Xss4M         --conf spark.executor.extraJavaOptions=-Xss4M         --conf spark.executor.memoryOverhead=5g         --conf spark.driver.maxResultSize=30g         --conf spark.kryoserializer.buffer.max=1g         --conf spark.memory.fraction=0.1         --conf spark.default.parallelism=1         --jars hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.driver.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.executor.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --py-files hail_builds/v01/hail-v01-10-8-2018-90c855449.zip         "hail_scripts/v01/load_dataset_to_es.py" "--genome-version" "37" "--project-guid" "R0001_project1" "--sample-type" "WES" "--dataset-type" "VARIANTS" "--skip-validation" "--exclude-hgmd" "--vep-block-size" "100" "--es-block-size" "10" "--num-shards" "1" "--use-nested-objects-for-vep" "--use-nested-objects-for-genotypes" "--output-vds" "GEN14" "file1.vcf.gz" "file2.vcf.gz" "file3.vcf.gz" --username 'thasan' --directory 'seqr03.nygenome.org:/usr/local/seqr/seqr/hail_elasticsearch_pipelines'
    ' returned non-zero exit status 2`

**Comment by Toseph** [comment]
Output w/o quotes error is 
`load_dataset_to_es.py: error: Input must be a .vds or .vcf.gz`


`./manual-upload.sh`
`/usr/local/seqr/seqr/../bin/spark-2.0.2-bin-hadoop2.7/bin/spark-submit         --master local[8]         --driver-memory 40G         --executor-memory 40G         --num-executors 10         --conf spark.driver.extraJavaOptions=-Xss4M         --conf spark.executor.extraJavaOptions=-Xss4M         --conf spark.executor.memoryOverhead=5g         --conf spark.driver.maxResultSize=30g         --conf spark.kryoserializer.buffer.max=1g         --conf spark.memory.fraction=0.1         --conf spark.default.parallelism=1         --jars hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.driver.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.executor.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --py-files hail_builds/v01/hail-v01-10-8-2018-90c855449.zip         "hail_scripts/v01/load_dataset_to_es.py" "--genome-version" "37" "--project-guid" "R0001_project1" "--sample-type" "WES" "--dataset-type" "VARIANTS" "--skip-validation" "--exclude-hgmd" "--vep-block-size" "100" "--es-block-size" "10" "--num-shards" "1" "--use-nested-objects-for-vep" "--use-nested-objects-for-genotypes" "--output-vds" "GEN14" "file*gz" --username 'thasan' --directory 'seqr03.nygenome.org:/usr/local/seqr/seqr/hail_elasticsearch_pipelines'`

`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: elasticsearch in /usr/lib/python2.7/site-packages (7.0.4)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python2.7/site-packages (from elasticsearch) (1.25.3)
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
usage: load_dataset_to_es.py [-h] --genome-version {37,38} [--skip-vep]
                             [--skip-annotations] [--skip-validation]
                             [--skip-writing-intermediate-vds]
                             [--filter-interval FILTER_INTERVAL]
                             [--remap-sample-ids REMAP_SAMPLE_IDS]
                             [--subset-samples SUBSET_SAMPLES]
                             [--ignore-extra-sample-ids-in-tables]
                             [--ignore-extra-sample-ids-in-vds]
                             [--fam-file FAM_FILE]
                             [--max-samples-per-index MAX_SAMPLES_PER_INDEX]
                             [--export-vcf] --project-guid PROJECT_GUID
                             [--family-id FAMILY_ID]
                             [--individual-id INDIVIDUAL_ID] --sample-type
                             {WES,WGS,RNA} --dataset-type {VARIANTS,SV}
                             [--not-gatk-genotypes] [--index INDEX]
                             [--host HOST] [--port PORT]
                             [--num-shards NUM_SHARDS]
                             [--use-temp-loading-nodes]
                             [--vep-block-size VEP_BLOCK_SIZE]
                             [--es-block-size ES_BLOCK_SIZE]
                             [--cpu-limit CPU_LIMIT]
                             [--use-nested-objects-for-vep]
                             [--use-nested-objects-for-genotypes]
                             [--use-child-docs-for-genotypes]
                             [--discard-missing-genotypes] [--exclude-dbnsfp]
                             [--exclude-1kg] [--exclude-omim]
                             [--exclude-gene-constraint] [--exclude-eigen]
                             [--exclude-cadd] [--exclude-gnomad]
                             [--exclude-exac] [--exclude-topmed]
                             [--exclude-clinvar] [--exclude-hgmd]
                             [--exclude-mpc] [--exclude-primate-ai]
                             [--exclude-splice-ai] [--exclude-gnomad-coverage]
                             [--exclude-vcf-info-field]
                             [--dont-update-operations-log]
                             [--dont-delete-intermediate-vds-files]
                             [--only-export-to-elasticsearch-at-the-end]
                             [--create-snapshot]
                             [--start-with-step {0,1,2,3,4}]
                             [--stop-after-step {0,1,2,3,4}]
                             [--start-with-sample-group START_WITH_SAMPLE_GROUP]
                             [--username USERNAME] [--directory DIRECTORY]
                             [--output-vds OUTPUT_VDS]
                             input_dataset`
`load_dataset_to_es.py: error: Input must be a .vds or .vcf.gz
Traceback (most recent call last):
  File "gcloud_dataproc/submit.py", line 99, in <module>
    subprocess.check_call(command, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/seqr/seqr/../bin/spark-2.0.2-bin-hadoop2.7/bin/spark-submit         --master local[8]         --driver-memory 40G         --executor-memory 40G         --num-executors 10         --conf spark.driver.extraJavaOptions=-Xss4M         --conf spark.executor.extraJavaOptions=-Xss4M         --conf spark.executor.memoryOverhead=5g         --conf spark.driver.maxResultSize=30g         --conf spark.kryoserializer.buffer.max=1g         --conf spark.memory.fraction=0.1         --conf spark.default.parallelism=1         --jars hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.driver.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.executor.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --py-files hail_builds/v01/hail-v01-10-8-2018-90c855449.zip         "hail_scripts/v01/load_dataset_to_es.py" "--genome-version" "37" "--project-guid" "R0001_project1" "--sample-type" "WES" "--dataset-type" "VARIANTS" "--skip-validation" "--exclude-hgmd" "--vep-block-size" "100" "--es-block-size" "10" "--num-shards" "1" "--use-nested-objects-for-vep" "--use-nested-objects-for-genotypes" "--output-vds" "GEN14" "file*gz" --username 'thasan' --directory 'seqr03.nygenome.org:/usr/local/seqr/seqr/hail_elasticsearch_pipelines'
    ' returned non-zero exit status 2`

**Comment by Toseph** [comment]
I noticed some options for family-ID and individual-ID, would it be worth trying those parameters to get this working?

**Comment by Toseph** [comment]
Also, could it be the python module that's doing the text parsing is not compatible or able to do this ? I can try pip installing/reinstalling whichever module it would be to test.

**Comment by nawatts** [comment]
`load_dataset_to_es.py` checks that input ends with one of ".vds", ".vcf", ".vcf.gz", or ".vcf.bgz".

https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/70de273b3cddce626e560b508be151f3d8ffa6b4/hail_scripts/v01/load_dataset_to_es.py#L144-L145

Instead of using "file*.gz" as the input glob, try "file*.vcf.gz".

**Comment by Toseph** [comment]
Just wanted to update and say that it seems to be working with "file*.vcf.gz" and using quotes around the "$INPUT". 

`2019-10-27 13:21:01,400 INFO
==> import: file*.vcf.gz
[Stage 0:======================================================>(665 + 1) / 666]2019-10-27 13:21:32 Hail: INFO: Multiallelic variants detected. Some methods require splitting or filtering multiallelics first.`

I will update later today/tomorrow on its status. Thank you as always and to the folks over on the seqr side of debug as well.

**Comment by Toseph** [comment]
I was able to submit my index that was generated from the wildcard submission, but it seems to only show against one sample still. My upload included three samples for both parent files and child, but seems to only have included the child index when you look at the bullet point.

I included a screenshot below, and I'm under the impression all bullet points against the sample would be filled-in if the index exists for each, but I could be wrong. 

<img width="219" alt="Screen Shot 2019-10-31 at 10 59 18 AM" src="https://user-images.githubusercontent.com/7651720/67958582-c85e4700-fbcd-11e9-868f-a72f1808b421.png">

I'm trying another mutli-vcf upload against a second family-set available in our seqr portal and will report on how it goes and if the index is linked against all three samples or just the one.

**Comment by hanars** [comment]
The filled in status isn't about loaded data, it indicates whether an individual is affected or unaffected, it is the standard way of representing pedigree information. Whether or not dat is loaded for an individual is indicated by a red/green dot on the right side of the panel, which you did not include in your screenshot

**Comment by Toseph** [comment]
Ah well in that case I do see the green dot on the side saying it was uploaded 10/30/19! 
<img width="1110" alt="Screen Shot 2019-10-31 at 3 49 43 PM" src="https://user-images.githubusercontent.com/7651720/67981062-328ae200-fbf6-11e9-9914-d906987265d7.png">

I'll touch base with our researcher and once I have his feedback we can close this out. 
This has been a great help for our project; thank you so much!

**Comment by hanars** [comment]
Hmm although I would expect to see all individuals in the family loaded and it looks like you only have data for the unaffected father, which doesn't sound right

**Comment by Toseph** [comment]
It worked for GEN14-05 in fact which I was almost sure was still uploading its index but is actually present (never did a multi-vcf upload for this either). So I will review GEN14-04 and try the multi-upload once more but with corrected filenames. 

<img width="1118" alt="Screen Shot 2019-11-01 at 10 25 00 AM" src="https://user-images.githubusercontent.com/7651720/68031860-db871a80-fc92-11e9-8ae0-1edae02f9dec.png">

**Comment by Toseph** [comment]
After trying to search for variants on the multi-vcf family datasets, I get this error. 
DSL class `None` does not exist in query. 

I am assuming this is because the samples are not able to be worked with properly. 
I'm reuploading the multi-dataset samples and will try to see if it changes that.

**Comment by hanars** [comment]
This is almost definitely an issue because you don't have all the samples in the same index, so the multi-dataset upload should fix that
