### ISSUE TITLE
Make it possible to change vep-config.json path via command-line arg for SeqrMTToESTask

### ISSUE THREAD

**Issue by bw2** [broadinstitute/hail-elasticsearch-pipelines#176]
Add a command line arg that makes it possible to change the vep config paths @
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/hail_scripts/v02/utils/hail_utils.py#L119
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/hail_scripts/v02/utils/hail_utils.py#L122

This allows different VEP paths for local installs, allows 
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/issues/165
to be fixed, etc.

**Comment by hanars** [comment]
If theres an optimized VEP config that works for seqr, why wouldn't we create that config and always use it? For example, for https://github.com/macarthur-lab/hail-elasticsearch-pipelines/issues/165 why would we want to keep the option to continue using a config that is 5 times slower?
