### ISSUE TITLE
Add command line and/or config file args to SeqrMTToESTask

### ISSUE THREAD

**Issue by bw2** [broadinstitute/hail-elasticsearch-pipelines#177]
The v01 pipeline supports these options on the command line

 --genome-version $GENOME_VERSION 
  --project-guid $PROJECT_GUID 
  --sample-type $SAMPLE_TYPE 
  --dataset-type $DATASET_TYPE 
  --vep-block-size 100 
  --es-block-size 10 
  --num-shards 1

Is there a way to set these for SeqrMTToESTask?

**Comment by hanars** [comment]
genome-version, project-guid, and sample-type all come from the config for the run. They are accessed as luigi parameters (https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/1e4c622150b8cec71502b2d1ecee24b0e93c47e9/luigi_pipeline/lib/hail_tasks.py#L44) and heres an example config file: https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/luigi_pipeline/configs/seqr-loading-local.cfg The production config files live here: https://github.com/macarthur-lab/All-The-Envs/tree/master/airflow/variables/vcf_config

num-shards is dynamically computed: https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/luigi_pipeline/lib/hail_tasks.py#L232

I think vep-block-size and es-block-size are no longer configurable
I think dataset-type isn't used?
