### ISSUE TITLE
What is the estimate for Hail 0.2 pipeline to be ready?

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/hail-elasticsearch-pipelines#179]
Hi,

I am wondering whether Hail 0.2 version is ready or not, whether we can already run the same pipelines in 0.2 as in 0.1 and if not, what is the estimate for it to be ready. 

Regards

**Comment by bw2** [comment]
Hi @NLSVTN 
I updated the local install scripts to the v02 pipeline as part of this PR
https://github.com/macarthur-lab/seqr/pull/1082

I still need to update the docs. Are you interested in running it on-prem or on gcloud dataproc?

**Comment by NLSVTN** [comment]
On prem and I will try accommodating it for AWS EMR also.
