### ISSUE TITLE
gcloud_dataproc scripts failing due to missing gcloud resource

### ISSUE THREAD

**Issue by ssadedin** [broadinstitute/hail-elasticsearch-pipelines#199]
Our import pipeline started failing today because it refers to a resource in google cloud storage that no longer seems to be available:

```
ERROR: (gcloud.beta.dataproc.clusters.create) INVALID_ARGUMENT: Google Cloud Storage object does not exist 'gs://hail-common/vep/vep/GRCh37/vep85-GRCh37-init.sh'.
```
I can see that it truly doesn't exist any more using `gsutil`. In fact, the parent folders serveral levels up have been removed, eg:

```
gsutil ls gs://hail-common/vep/
CommandException: One or more URLs matched no objects.
```

However the content is still referenced by the scripts in this repo - eg:

https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/gcloud_dataproc/v01/create_cluster_GRCh37.py

Any guidance on whether this content was intentionally removed (if so, is there another location we can point to) or if it can be restored?

**Comment by nawatts** [comment]
Hi @ssadedin,

This was a change by the Hail project.

> The data sources for VEP have been moved to gs://hail-us-vep, gs://hail-eu-vep, and gs://hail-uk-vep, which are requester-pays buckets in Google Cloud. hailctl dataproc will automatically infer which of these buckets you should pull data from based on the region your cluster is spun up in. If you are in none of those regions, please contact us on discuss.hail.is.
> -- https://hail.is/docs/0.2/change_log.html#version-0-2-34
