### ISSUE TITLE
Generate new binaries for Hail

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/hail-elasticsearch-pipelines#214]
In the folder: 

https://github.com/broadinstitute/hail-elasticsearch-pipelines/tree/master/hail_builds/v02

There are hail binaries that were made from already rather outdated hail, so I want to generate it myself from source somehow. Could you point me to the code that did that?

**Comment by hanars** [comment]
@bw2 can you link to the script you used to generate these?

Also, I can't promise that the pipeline will work with a different hail version

**Comment by hanars** [comment]
the latest pipeline does not use these binaries
