### ISSUE TITLE
Loading SV data into ES - nothing written

### ISSUE THREAD

**Issue by williamphu** [broadinstitute/hail-elasticsearch-pipelines#221]
Following up with an issue from last week. Ran 
```./load_data.py ~/Documents/Seqr_SV/cmg_main_output_2021_01_08_StrVCTVRE_fixedColumns_fixedSampleNames.bed --in-silico ~/Documents/Seqr_SV/cmg_main_output_2021_01_08_StrVCTVRE_fixedColumns_fixedSampleNames.bed --project-guid R0542_aicardi_wes --ignore-missing-samples``` and got the output ```
INFO:__main__:Exporting 2227 docs to ES index r0542_aicardi_wes__structural_variants__wes__grch38__20210108```. However Kibana shows there is nothing in the document.

**Comment by hanars** [comment]
can you attach here or slack me the data and in-silico bed files

**Comment by hanars** [comment]
Loading data worked for me with no issues, so closing this out and hoping for the best next time
