### ISSUE TITLE
VCF FILE FILTERING FUNCTION

### ISSUE THREAD

**Issue by ap1438** [broadinstitute/hail-elasticsearch-pipelines#223]
Hi

How do i filter the vcf file using below filters:

    number of reads per base is between 5 and 75
    base quality > or = to 30
    mapping quality >= 60
    variant quality >= 90
    distance of adjacent variant >= 5

Can you please suggest the options to be used to filter

**Comment by hanars** [comment]
This repository is for running a loading pipeline for the seqr application, not for VCF processing in general. I think maybe you want to reach out tothe hail group directly for general VCFquestions
