### ISSUE TITLE
Copying reference data to Australian bucket

### ISSUE THREAD

**Issue by illusional** [broadinstitute/hail-elasticsearch-pipelines#225]
Hi! We're planning to use this data a bit to generate annotations for seqr, and thought it might be worthwhile to create an Australian mirror of this data to save some egress.

```
ref_data_path = "gs://seqr-reference-data/GRCh38/all_reference_data/combined_reference_data_grch38.ht"
clinvar_path = "gs://seqr-reference-data/GRCh38/clinvar/clinvar.GRCh38.2020-06-15.ht"
```

Wondering if there's a suggested way of doing this, or if there's an easy way to generate this data.

Thanks in advance!

**Comment by hanars** [comment]
We strongly recommend you use the on-prem annotation option described in the local install readme:
https://github.com/broadinstitute/seqr/blob/master/deploy/LOCAL_INSTALL.md#annotating-and-loading-vcf-callsets---option-2-annotate-and-load-on-prem

This will cause you to only pay for egress on these resources one time which we consider to be a reasonable cost. We don't really have the funds to pay for a mirror of this data

**Comment by illusional** [comment]
Thanks for the info! We only have GCP, so no on-prem. We're happy to host it, more just checking to see if there are any issues copying it to an Australian bucket before I do it.

**Comment by hanars** [comment]
you can still follow the instructions to copy the files and run the pipeline using your own copies, which you can host on your own GCP instance. We would strongly prefer this, as accessing the files on our GCP instance every time you load data will be prohibitively expensive for us
