### ISSUE TITLE
Gnomad 3.1.1 genomes combined reference issue

### ISSUE THREAD

**Issue by gilmorera** [broadinstitute/hail-elasticsearch-pipelines#226]
I'm having some issue with the new Gnomad 3.1.1 version.  I've downloaded the 3.1.1 hail table:

`gs://gcp-public-data--gnomad/release/3.1.1/ht/genomes/gnomad.genomes.v3.1.1.sites.ht`

And attempted to generate the combined hail table via [write_combined_reference_data_ht.py](https://github.com/broadinstitute/hail-elasticsearch-pipelines/blob/master/download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py)

The hangup seems to be in the custom select function at line 227:
https://github.com/broadinstitute/hail-elasticsearch-pipelines/blob/e2a7e08b356ce70af314507908c7df4a9f128d7b/download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py#L210-L228

Here is my error:

```HailException: Key 'adj_male'    not found in dictionary. Keys: ["10-afr-adj","```

**Comment by mike-w-wilson** [comment]
Thanks for pointing this out @gilmorera , we need to update the custom select to reflect the new hail frequency schema. This  will be address with #240

**Comment by gilmorera** [comment]
No problem @mike-w-wilson .  I ended up fixing this by changing the item in this line:

https://github.com/broadinstitute/hail-elasticsearch-pipelines/blob/a12cf68c733c1937cd8334a9cba86fec8d34a95b/download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py#L227

from '_adj_male_' to '_XY-adj_'.  And I was able to complete the hail table without errors.
