### ISSUE TITLE
sortedTranscriptConsequences is empty for some variants

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/hail-elasticsearch-pipelines#248]
Hi,

We noticed that we see no **transcriptIds, mainTranscriptId, gene_ids** calculated in the pipeline (luigi pipeline) for some variants. These annotations depend upon **sorted_transcript_consequences** annotation:

https://github.com/broadinstitute/hail-elasticsearch-pipelines/blob/master/luigi_pipeline/lib/model/seqr_mt_schema.py#L105-L116

Our VEP seems to be just fine: we are using your json config that we found on google cloud. So, we are wondering whether the issue could come from the function:

https://github.com/broadinstitute/hail-elasticsearch-pipelines/blob/master/hail_scripts/v02/utils/computed_fields/vep.py#L132

Have you ever faced such an issue? Any ideas?

**Comment by hanars** [comment]
There are intergenic variants that do not fall in any annotated transcript. This is quite normal

**Comment by ranganathangas2** [comment]
Hi,

We have also found a similar issue where a missense variant (**chr4: 113358472- T -C**), in the index has null values for transcriptIds, mainTranscriptId, gene_ids. 

Our VEP output seems fine and it has annotated the variant with the correct gene symbols (or gene ID) but it doesn't show up in our index. 

We understand this scenario may be common with intergenic variant, but not sure on why it is happening with a missense variant? It would be great if you could provide some insights on this.

**Comment by hanars** [comment]
This seems to be a bug somewhere in the pipeline. Did you load the data using the latest version of the pipeline code?
