### ISSUE TITLE
Add validating MT arg to airflow 

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/hail-elasticsearch-pipelines#254]
Currently, the luigi pipeline  supports not validating the input VCF/MT: https://github.com/broadinstitute/hail-elasticsearch-pipelines/blob/e2a7e08b356ce70af314507908c7df4a9f128d7b/luigi_pipeline/seqr_loading.py#L63

Airflow does not build or pass this argument: https://github.com/broadinstitute/seqr-pipeline-airflow/blob/0f85b2bb5acd063f1d7378cf929d984f6c376833/airflow/dags/seqr-vcf-to-es.py#L304

**Comment by mike-w-wilson** [comment]
Added in #53 https://github.com/broadinstitute/seqr-pipeline-airflow/pull/53

**Comment by williamphu** [comment]
Updated fix in #54 [broadinstitute/seqr-pipeline-airflow#54](https://github.com/broadinstitute/seqr-pipeline-airflow/pull/54)

**Comment by williamphu** [comment]
Resolved in the seqr-airflow commit https://github.com/broadinstitute/seqr-pipeline-airflow/commit/ca918cc876332a128da233f6a3e3123f618d2b6b
