### ISSUE TITLE
Update FATHMM

### ISSUE THREAD

**Issue by hanars** [broadinstitute/hail-elasticsearch-pipelines#264]
From https://github.com/broadinstitute/seqr/issues/2027

Update to FATHMM_MKL which includes annotations for noncoding variants - http://fathmm.biocompute.org.uk/fathmmMKL.htm

**Comment by mike-w-wilson** [comment]
This score is within the dbSNFP dataset so we can to pull the annotation from there

**Comment by mike-w-wilson** [comment]
Updated here: gs://seqr-reference-data/GRCh38/dbNSFP/v4.2/dbNSFP4.2a_variant.ht 
Will combine with other ref data once other datasets are updated.

**Comment by mike-w-wilson** [comment]
https://github.com/broadinstitute/hail-elasticsearch-pipelines/pull/285
https://github.com/broadinstitute/seqr-pipeline-airflow/pull/60
