### ISSUE TITLE
NaN issue with NAN* annotated genes from VEP

### ISSUE THREAD

**Issue by karynne7** [broadinstitute/hail-elasticsearch-pipelines#265]
My error: "... Hail version: 0.2.74-0c3a74d12093
Error summary: JsonParseException: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
 at [Source: UNKNOWN; line: 1, column: 395] ..."

If I remove any "NAN*" annotated genes from my VCF (WES or WGS) I am able to upload them with hailctl. However, I get these NaN errors if they are included. I believe I am using the latest versions on the GCP, any ideas helpful! Thanks!

My command: 
hailctl dataproc submit seqr-loading-cluster37     seqr_loading.py --pyfiles "lib,../hail_scripts"     SeqrVCFToMTTask --local-scheduler  --source-paths gs://uw-mgrc/seqr_udn_ucla_external_uwcmg_fam287604_1.noNAN.vcf.gz --dest-path gs://uw-mgrc/seqr_udn.mt --genome-version 37   --sample-type WGS --reference-ht-path  gs://uw-mgrc/data/seqr-reference-data/GRCh37/combined_reference_data_grch37.ht --clinvar-ht-path gs://uw-mgrc/data/seqr-reference-data/GRCh37/clinvar.GRCh37.2020-06-15.ht --dont-validate

**Comment by hanars** [comment]
Our pipeline runs VEP so your input VCF should not already have any VEP annotations in it to start with

**Comment by karynne7** [comment]
It does not have VEP annotations. However, I have run the VCF through VEP before, so I knew which variants to leave out to get around the NAN issue.

**Comment by hanars** [comment]
@mike-w-wilson have we ever run in to this issue with our pipeline before?

**Comment by mike-w-wilson** [comment]
We have not run into this issue before. I'm not sure how this would be handled differently in our pipeline unless it is a VEP config difference. Which VEP config is being used for this run?

**Comment by karynne7** [comment]
I am using GRCh37 options, but not specifying a json for VEP. Should I try with a specific file? I had gotten errors about not finding the /vep_data/ directory when I tried before, so I thought that direction might not have been the answer.

**Comment by hanars** [comment]
If you are following the on-prem loading instructions we provide you should have a `--vep-config-json-path` specified: https://github.com/broadinstitute/seqr/blob/master/deploy/LOCAL_INSTALL.md#option-2-annotate-and-load-on-prem

**Comment by karynne7** [comment]
As you can see from my command I listed, ("hailctl dataproc submit ..") that I've been trying option one. It does not specify using that argument, but if you think I need to set up a config file differently, I'd be happy to take some advice on where to update it and try it.

**Comment by hanars** [comment]
are you correctly setting the `--vep` argument when you set up the cluster with `hailctl dataproc start`?

**Comment by hanars** [comment]
hmm that looks right to me too. @bw2 have you ever seen this sort of error?

**Comment by karynne7** [comment]
I loaded a grc38 genome just fine today. So I think the issue is either with the liftover or the VEP configuration of 37? Any ideas of what I can test next?

**Comment by hanars** [comment]
@bw2 is it possible we have a corrupted grch37 reference file somewhere?

**Comment by mike-w-wilson** [comment]
After searching zulip hail messages, this is a vep 85 config issue. Our pipeline uses hail's built in vep module: https://hail.is/docs/0.2/methods/genetics.html#hail.methods.vep which has a `tolerate_parse_error ` argument to account for the vep issue. This defaults to False in our pipeline. Documentation states: `tolerate_parse_error (bool) – If True, ignore invalid JSON produced by VEP and return a missing annotation.` @karynne7 if you add this arg, `tolerate_parse_error=True` to this line: https://github.com/broadinstitute/hail-elasticsearch-pipelines/blob/60256431fd7bd58cada03fe869b876b9ec931a5f/hail_scripts/v02/utils/hail_utils.py#L126 I believe the pipeline will run.

**Comment by karynne7** [comment]
I was able to get a GRCh37 exome trio to load! Thank you so much. Trying a whole genome run now to be sure.

**Comment by karynne7** [comment]
The genome worked as well. Thanks so much, everyone!
