### ISSUE TITLE
Update topmed data

### ISSUE THREAD

**Issue by hanars** [broadinstitute/hail-elasticsearch-pipelines#266]
Current data is from is from Nov 2018, should be updated

**Comment by mike-w-wilson** [comment]
Freeze 8 is downloaded here: gs://seqr-reference-data/GRCh38/TopMed/freeze8

**Comment by mike-w-wilson** [comment]
https://console.cloud.google.com/dataproc/jobs/7fe4e76b61984605a17e4b7b874ee259/monitoring?region=us-central1&authuser=0&project=seqr-project

**Comment by mike-w-wilson** [comment]
https://github.com/broadinstitute/hail-elasticsearch-pipelines/pull/285
https://github.com/broadinstitute/seqr-pipeline-airflow/pull/60
