### ISSUE TITLE
New TOPMed reference data uses a list for AF instead of a float

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/hail-elasticsearch-pipelines#291]
This is breaking seqr's search. The TOPMed table needs to be updated and then the combined reference script needs to run again. Airflow is currently pointing at 2.0.4 for GRCh38 which has the bug. We can revert to 2.0.3 if the fix is more challenging than anticipated.

**Comment by mike-w-wilson** [comment]
We need to determine if the list contains both ref and alt frequencies or is just a single entry list. Reviewing the previous TOPMed version VCF and HT should help clear this up. We can update the single annotation instead of running the entire combine script again.

**Comment by mike-w-wilson** [comment]
Lists were a single entry for all topmed annotations. I updated this by transmuting the field by grabbing the first and only entry in the list. I verified all data types match the 2.0.3 and rewrote gs://seqr-reference-data/GRCh38/all_reference_data/v2/combined_reference_data_grch38-2.0.4.ht

**Comment by gilmorera** [comment]
Hi @mike-w-wilson.  We recently downloaded the TopMed Hail Table (`updates/2022.4/data/combined/write_combined_ht_gnomad3.sh`) and used it to build the combined reference hail table.  However, we are now having issues with the variant search in our instance of seqr.  Was this a manual fix of the combined reference table or is there a fix in the scripting somewhere?

**Comment by gilmorera** [comment]
This happens for other fields as well:
```python
# Freeze 5
In [8]: comb_old.topmed.show(2)
+---------------+------------+-----------+-----------+-----------+------------+------------+
| locus         | alleles    | topmed.AC | topmed.AF | topmed.AN | topmed.Hom | topmed.Het |
+---------------+------------+-----------+-----------+-----------+------------+------------+
| locus<GRCh38> | array<str> |     int32 |   float64 |     int32 |      int32 |      int32 |
+---------------+------------+-----------+-----------+-----------+------------+------------+
| chr1:10001    | ["T","A"]  |        NA |        NA |        NA |         NA |         NA |
| chr1:10001    | ["T","C"]  |        NA |        NA |        NA |         NA |         NA |
+---------------+------------+-----------+-----------+-----------+------------+------------+
showing top 2 rows




# Freeze 8
In [9]: comb_new.topmed.show(2)
+---------------+------------+--------------+----------------+-----------+--------------+--------------+
| locus         | alleles    | topmed.AC    | topmed.AF      | topmed.AN | topmed.Hom   | topmed.Het   |
+---------------+------------+--------------+----------------+-----------+--------------+--------------+
| locus<GRCh38> | array<str> | array<int32> | array<float64> |     int32 | array<int32> | array<int32> |
+---------------+------------+--------------+----------------+-----------+--------------+--------------+
| chr1:10001    | ["T","A"]  | NA           | NA             |        NA | NA           | NA           |
| chr1:10001    | ["T","C"]  | NA           | NA             |        NA | NA           | NA           |
+---------------+------------+--------------+----------------+-----------+--------------+--------------+
```
