### ISSUE TITLE
Apache Log4j 2 vulnerability

### ISSUE THREAD

**Issue by karynne7** [broadinstitute/hail-elasticsearch-pipelines#294]
According to google, the dataproc has potential for a vulnerabilty and they asked us to make new images.
"Due to an Apache Log4j 2 vulnerability, all Dataproc images that were released prior to December 12, 2021 will be deprecated on January 17, 2022. " https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.0

I'm not sure that is something I can easily update on my end, as the seqr_loading.py script calls these hail directories with a versioning hard coded in. Is 2.0.6 ok, or do we need to update to something past last Sunday? 
gs://hail-common/hailctl/dataproc/0.2.77/ 
hailtop/hailctl/dataproc/start.py:IMAGE_VERSION = '2.0.6-debian10'

Thanks for any advice on this.

**Comment by hanars** [comment]
The hail team has said they will be releasing an update shortly, so once they do you should be able to use that. If there are any updates needed within this repo, we will update and release a new version as well

https://discuss.hail.is/t/log4j-vulnerability-in-dataproc-how-to-update/2408
