### ISSUE TITLE
Look into mapping gene names through genecards.

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/hail-elasticsearch-pipelines#304]
Analysts are attempting to make gene lists but are hitting issues when the gene name is outdated. This is a consequence of using older versions ofVEP v95/v85. We plan on updating VEP with gnomAD but a quick fix would be to map and annotate all old gene names to new ones. https://www.genecards.org/

**Comment by hanars** [comment]
seqr does not pull geen lists for search purposes from the pipeline, so no pipeline change can help this issue. See https://github.com/broadinstitute/seqr/issues/2301 for discussion of updating gencode in the seqr reference data databse
