### ISSUE TITLE
Fail airflow task if removing samples from loading

### ISSUE THREAD

**Issue by hanars** [broadinstitute/hail-elasticsearch-pipelines#339]
For the task to compute the project subset from airtable, we should add a check that if there was already a project subset file we are not removing any samples from it. If there are any samples that were in the subset that are no longer coming back from airtable, the task should fail without writing a new subset file and the rest of the pipeline should not run

**Comment by mike-w-wilson** [comment]
Done in: https://github.com/broadinstitute/seqr-pipeline-airflow/pull/77/files

**Comment by mike-w-wilson** [comment]
Last test is blocked until our sendgrid license is reactivated.
